Baitap5_63130230/Baitap5_63130230/Models/EmpModel.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;

namespace Baitap5_63132131.Models
{
    public class EmpModel
    {
        public string EmpID { get; set; }
        public string Name { get; set; }
        public DateTime BirthOfDate { get; set; }
        public string Email { get; set; }
        public string Password { get; set; }
        public string Department { get; set; }
        public string Avatar { get; set; }

    }
}

Baitap5_63130230/Baitap5_63130230/Models/MailInfo.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;

namespace Baitap5_63132131.Models
{
    public class MailInfo
    {
        public string From { get; set; }
        public string Password { get; set; }
        public string To { get; set; }
        public string Subject { get; set; }
        public string Body { get; set; }
    }
}

Baitap5_63130230/Baitap5_63130230/Controllers/ChangeBanner_63132131Controller.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace BaiTap5_63130230.Controllers
{
    public class ChangeBanner_63132131Controller : Controller
    {
        // GET: ChangeBanner_63130230
        public ActionResult Index()
        {
            return View();
        }
        public ActionResult ChangeBanner()
        {
            return View();
        }
        [HttpPost]
        public ActionResult ChangeBanner(HttpPostedFileBase banner)
        {
            string postedFileName =
           System.IO.Path.GetFileName(banner.FileName);
            var path = Server.MapPath("/Images/" + postedFileName);
            banner.SaveAs(path);
            string fSave = Server.MapPath("/banner.txt");
            System.IO.File.WriteAllText(fSave, postedFileName);
            return View();
        }

    }
}

Baitap5_63130230/Baitap5_63130230/Controllers/GuiEmail_63132131Controller.cs
using Baitap5_63132131.Models;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace BaiTap5_63132131.Controllers
{
    public class GuiEmail_63132131Controller : Controller
    {
        // GET: GuiEmail_63132131
        public ActionResult Index1()
        {
            return View();
        }
        [HttpPost]
        public ActionResult Index1(MailInfo model)
        {
            System.Net.Mail.MailMessage mail = new System.Net.Mail.MailMessage();
            mail.From = new System.Net.Mail.MailAddress(model.From);
            mail.To.Add(model.To);
            mail.Subject = model.Subject;
            mail.Body = model.Body;
            mail.IsBodyHtml = true;
            System.Net.Mail.SmtpClient smtp = new System.Net.Mail.SmtpClient("smtp.gmail.com", 587);
            smtp.Credentials = new System.Net.NetworkCredential(model.From, model.Password);
            smtp.EnableSsl = true;
            smtp.Send(mail);
            return Content("Đã gửi Email");
        }
    }
}

Baitap5_63130230/Baitap5_63130230/Controllers/HomeController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace Baitap5_63130230.Controllers
{
    public class HomeController : Controller
    {
        public ActionResult Index()
        {
            return View();
        }

        public ActionResult About()
        {
            ViewBag.Message = "Your application description page.";

            return View();
        }

        public ActionResult Contact()
        {
            ViewBag.Message = "Your contact page.";

            return View();
        }
    }
}

Baitap5_63130230/Baitap5_63130230/Controllers/NhanVien_63132131Controller.cs
using Baitap5_63132131.Models;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace Baitap5_63132131.Controllers
{
    public class NhanVien_63132131Controller : Controller
    {
        // GET: NhanVien_63132131
        public ActionResult Index()
        {
            return View();
        }
    
    [HttpPost]
    public ActionResult Index(HttpPostedFileBase Avatar, EmpModel emp)
    {
        //Lấy thông tin từ input type=file có tên Avatar
        string postedFileName = System.IO.Path.GetFileName(Avatar.FileName);
        //Lưu hình đại diện về Server
        var path = Server.MapPath("/Images/" + postedFileName);
        Avatar.SaveAs(path);
        string fSave = Server.MapPath("/emp.txt");
        string[] emInfo =
       {emp.EmpID, emp.Name, emp.BirthOfDate.ToShortDateString(),
 emp.Email,emp.Password,emp.Department, postedFileName};
        //Lưu các thông ti vào tập tin emp.txt
        System.IO.File.WriteAllLines(fSave, emInfo);
        //Ghi nhận các thông tin đăng ký để hiện thị trên View Confirm
        ViewBag.EmpID = emInfo[0];
        ViewBag.Name = emInfo[1];
        ViewBag.BirthOfDate = emInfo[2].ToString();
        ViewBag.Email = emInfo[3];
        ViewBag.Password = emInfo[4];
        ViewBag.Department = emInfo[5];
        ViewBag.Avatar = "/Images/" + emInfo[6];
        return View("Confirm");
    }
    public ActionResult Confirm()
    {
        return View();
    }
}
}

Baitap5_63130230/Baitap5_63130230/Controllers/TrangChu_63132131Controller.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace Baitap5_63130230.Controllers
{
    public class TrangChu_63132131Controller : Controller
    {
        // GET: TrangChu_63130230
        public ActionResult Default()
        {
            return View();
        }
    }
}

Baitap5_63130230/Baitap5_63130230/Views/ChangeBanner_63132131/ChangeBanner.cshtml
@{
    ViewBag.Title = "ChangeBanner";
    Layout = "~/Views/Shared/_LayoutAdmin.cshtml";
}
@using (Html.BeginForm("ChangeBanner", "ChangeBanner_63130230",
FormMethod.Post, new { enctype = "multipart/form-data" }))
{
    <p>
        <h3> <b>THAY ĐỔI BANNER</b></h3>
    </p>
    <hr />
    <p>
        Chọn ảnh làm banner: &nbsp;<input type="file" style="height:30px;" name="banner" accept="image/*" required /><br>
        <input type="submit" style="height:30px;" value="Thay đổi" /><br>
    </p>
}

Baitap5_63130230/Baitap5_63130230/Views/NhanVien_63132131/Confirm.cshtml
@{
    ViewBag.Title = "Confirm";
    Layout = "~/Views/Shared/_LayoutAdmin.cshtml";
}

<h3>THÔNG TIN THÀNH VIÊN ĐÃ ĐĂNG KÝ</h3>
<img src="@ViewBag.Avatar" />
<br />
Mã số nhân viên: @ViewBag.EmpID
<br />
Họ tên: @ViewBag.Name
<br />
Ngày sinh: @ViewBag.BirthOfDate
<br />
Email: @ViewBag.Email
<br />
Mật khẩu: @ViewBag.Password
<br />
Đơn vị: @ViewBag.Department
<br />
Avatar: @ViewBag.Avatar

Baitap5_63130230/Baitap5_63130230/Views/NhanVien_63132131/Index.cshtml
@model Baitap5_63132131.Models.EmpModel

@{
    ViewBag.Title = "Index";
    Layout = "~/Views/Shared/_LayoutAdmin.cshtml";
}

<h2>Index</h2>

@using (Html.BeginForm("Index", "NhanVien_63132131", FormMethod.Post, new { enctype = "multipart/form-data" }))
{
    @Html.AntiForgeryToken()

    <div class="form-horizontal">
        <h4>THÔNG TIN THÀNH VIÊN ĐĂNG KÝ</h4>
        <hr />
        @Html.ValidationSummary(true, "", new { @class = "text-danger" })
        <div class="form-group">
            @Html.LabelFor(model => model.EmpID, "Mã số nhân viên", htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.EmpID, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.EmpID, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Name, "Họ tên", htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Name, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Name, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.BirthOfDate, "Ngày sinh", htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.BirthOfDate, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.BirthOfDate, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Email, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Email, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Email, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Password, "Mật khẩu", htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.PasswordFor(model => model.Password, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Password, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Department, "Đơn vị", htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Department, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Department, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Avatar, "Ảnh đại diện", htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                <input type="file" name="Avatar" />
                @Html.ValidationMessageFor(model => model.Avatar, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <input type="submit" value="Create" class="btn btn-default" />
            </div>
        </div>
    </div>
}

<div>
    @Html.ActionLink("Back to List", "Index")
</div>