BT6_63130516/BT6_63130516/Controllers/NhanViens63130516Controller.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.Linq;
using System.Net;
using System.Web;
using System.Web.Mvc;
using BT6_63130516.Models;

namespace BT6_63130516.Controllers
{
    public class NhanViens63130516Controller : Controller
    {
        private QLNV_63130516Entities db = new QLNV_63130516Entities();

        // GET: NhanViens63130516
        public ActionResult Index()
        {
            var nhanViens = db.NhanViens.Include(n => n.PhongBan);
            return View(nhanViens.ToList());
        }

        // GET: NhanViens63130516/Details/5
        public ActionResult Details(string id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            NhanVien nhanVien = db.NhanViens.Find(id);
            if (nhanVien == null)
            {
                return HttpNotFound();
            }
            return View(nhanVien);
        }

        // GET: NhanViens63130516/Create
        public ActionResult Create()
        {
            ViewBag.MaPB = new SelectList(db.PhongBans, "MaPB", "TenPB");
            return View();
        }

        // POST: NhanViens63130516/Create
        // To protect from overposting attacks, enable the specific properties you want to bind to, for 
        // more details see https://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Create([Bind(Include = "MaNV,HoNV,TenNV,GioiTinh,NgaySinh,Luong,AnhNV,DiaChi,MaPB")] NhanVien nhanVien)
        {
            if (ModelState.IsValid)
            {
                db.NhanViens.Add(nhanVien);
                db.SaveChanges();
                return RedirectToAction("Index");
            }

            ViewBag.MaPB = new SelectList(db.PhongBans, "MaPB", "TenPB", nhanVien.MaPB);
            return View(nhanVien);
        }

        // GET: NhanViens63130516/Edit/5
        public ActionResult Edit(string id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            NhanVien nhanVien = db.NhanViens.Find(id);
            if (nhanVien == null)
            {
                return HttpNotFound();
            }
            ViewBag.MaPB = new SelectList(db.PhongBans, "MaPB", "TenPB", nhanVien.MaPB);
            return View(nhanVien);
        }

        // POST: NhanViens63130516/Edit/5
        // To protect from overposting attacks, enable the specific properties you want to bind to, for 
        // more details see https://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Edit([Bind(Include = "MaNV,HoNV,TenNV,GioiTinh,NgaySinh,Luong,AnhNV,DiaChi,MaPB")] NhanVien nhanVien)
        {
            if (ModelState.IsValid)
            {
                db.Entry(nhanVien).State = EntityState.Modified;
                db.SaveChanges();
                return RedirectToAction("Index");
            }
            ViewBag.MaPB = new SelectList(db.PhongBans, "MaPB", "TenPB", nhanVien.MaPB);
            return View(nhanVien);
        }

        // GET: NhanViens63130516/Delete/5
        public ActionResult Delete(string id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            NhanVien nhanVien = db.NhanViens.Find(id);
            if (nhanVien == null)
            {
                return HttpNotFound();
            }
            return View(nhanVien);
        }

        // POST: NhanViens63130516/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public ActionResult DeleteConfirmed(string id)
        {
            NhanVien nhanVien = db.NhanViens.Find(id);
            db.NhanViens.Remove(nhanVien);
            db.SaveChanges();
            return RedirectToAction("Index");
        }

        protected override void Dispose(bool disposing)
        {
            if (disposing)
            {
                db.Dispose();
            }
            base.Dispose(disposing);
        }
    }
}

BT6_63130516/BT6_63130516/Views/NhanViens63130516/Create.cshtml
@model BT6_63130516.Models.NhanVien

@{
    ViewBag.Title = "Create";
}

<h2>Create</h2>


@using (Html.BeginForm()) 
{
    @Html.AntiForgeryToken()
    
    <div class="form-horizontal">
        <h4>NhanVien</h4>
        <hr />
        @Html.ValidationSummary(true, "", new { @class = "text-danger" })
        <div class="form-group">
            @Html.LabelFor(model => model.MaNV, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.MaNV, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.MaNV, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.HoNV, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.HoNV, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.HoNV, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.TenNV, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.TenNV, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.TenNV, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.GioiTinh, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                <div class="checkbox">
                    @Html.EditorFor(model => model.GioiTinh)
                    @Html.ValidationMessageFor(model => model.GioiTinh, "", new { @class = "text-danger" })
                </div>
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.NgaySinh, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.NgaySinh, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.NgaySinh, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Luong, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Luong, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Luong, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.AnhNV, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.AnhNV, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.AnhNV, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.DiaChi, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.DiaChi, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.DiaChi, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.MaPB, "MaPB", htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.DropDownList("MaPB", null, htmlAttributes: new { @class = "form-control" })
                @Html.ValidationMessageFor(model => model.MaPB, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <input type="submit" value="Create" class="btn btn-default" />
            </div>
        </div>
    </div>
}

<div>
    @Html.ActionLink("Back to List", "Index")
</div>

@section Scripts {
    @Scripts.Render("~/bundles/jqueryval")
}

BT6_63130516/BT6_63130516/Views/NhanViens63130516/Delete.cshtml
@model BT6_63130516.Models.NhanVien

@{
    ViewBag.Title = "Delete";
}

<h2>Delete</h2>

<h3>Are you sure you want to delete this?</h3>
<div>
    <h4>NhanVien</h4>
    <hr />
    <dl class="dl-horizontal">
        <dt>
            @Html.DisplayNameFor(model => model.HoNV)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.HoNV)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.TenNV)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.TenNV)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.GioiTinh)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.GioiTinh)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.NgaySinh)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.NgaySinh)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Luong)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Luong)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.AnhNV)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.AnhNV)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.DiaChi)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.DiaChi)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.PhongBan.TenPB)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.PhongBan.TenPB)
        </dd>

    </dl>

    @using (Html.BeginForm()) {
        @Html.AntiForgeryToken()

        <div class="form-actions no-color">
            <input type="submit" value="Delete" class="btn btn-default" /> |
            @Html.ActionLink("Back to List", "Index")
        </div>
    }
</div>

BT6_63130516/BT6_63130516/Views/NhanViens63130516/Details.cshtml
@model BT6_63130516.Models.NhanVien

@{
    ViewBag.Title = "Details";
}

<h2>Details</h2>

<div>
    <h4>NhanVien</h4>
    <hr />
    <dl class="dl-horizontal">
        <dt>
            @Html.DisplayNameFor(model => model.HoNV)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.HoNV)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.TenNV)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.TenNV)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.GioiTinh)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.GioiTinh)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.NgaySinh)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.NgaySinh)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Luong)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Luong)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.AnhNV)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.AnhNV)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.DiaChi)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.DiaChi)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.PhongBan.TenPB)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.PhongBan.TenPB)
        </dd>

    </dl>
</div>
<p>
    @Html.ActionLink("Edit", "Edit", new { id = Model.MaNV }) |
    @Html.ActionLink("Back to List", "Index")
</p>

BT6_63130516/BT6_63130516/Views/NhanViens63130516/Edit.cshtml
@model BT6_63130516.Models.NhanVien

@{
    ViewBag.Title = "Edit";
}

<h2>Edit</h2>


@using (Html.BeginForm())
{
    @Html.AntiForgeryToken()
    
    <div class="form-horizontal">
        <h4>NhanVien</h4>
        <hr />
        @Html.ValidationSummary(true, "", new { @class = "text-danger" })
        @Html.HiddenFor(model => model.MaNV)

        <div class="form-group">
            @Html.LabelFor(model => model.HoNV, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.HoNV, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.HoNV, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.TenNV, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.TenNV, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.TenNV, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.GioiTinh, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                <div class="checkbox">
                    @Html.EditorFor(model => model.GioiTinh)
                    @Html.ValidationMessageFor(model => model.GioiTinh, "", new { @class = "text-danger" })
                </div>
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.NgaySinh, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.NgaySinh, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.NgaySinh, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Luong, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Luong, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Luong, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.AnhNV, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.AnhNV, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.AnhNV, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.DiaChi, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.DiaChi, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.DiaChi, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.MaPB, "MaPB", htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.DropDownList("MaPB", null, htmlAttributes: new { @class = "form-control" })
                @Html.ValidationMessageFor(model => model.MaPB, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <input type="submit" value="Save" class="btn btn-default" />
            </div>
        </div>
    </div>
}

<div>
    @Html.ActionLink("Back to List", "Index")
</div>

@section Scripts {
    @Scripts.Render("~/bundles/jqueryval")
}

BT6_63130516/BT6_63130516/Views/NhanViens63130516/Index.cshtml
@model IEnumerable<BT6_63130516.Models.NhanVien>

@{
    ViewBag.Title = "Index";
}

<h2>Index</h2>

<p>
    @Html.ActionLink("Create New", "Create")
</p>
<table class="table">
    <tr>
        <th>
            @Html.DisplayNameFor(model => model.HoNV)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.TenNV)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.GioiTinh)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.NgaySinh)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.Luong)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.AnhNV)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.DiaChi)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.PhongBan.TenPB)
        </th>
        <th></th>
    </tr>

@foreach (var item in Model) {
    <tr>
        <td>
            @Html.DisplayFor(modelItem => item.HoNV)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.TenNV)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.GioiTinh)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.NgaySinh)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.Luong)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.AnhNV)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.DiaChi)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.PhongBan.TenPB)
        </td>
        <td>
            @Html.ActionLink("Edit", "Edit", new { id=item.MaNV }) |
            @Html.ActionLink("Details", "Details", new { id=item.MaNV }) |
            @Html.ActionLink("Delete", "Delete", new { id=item.MaNV })
        </td>
    </tr>
}

</table>

BT6_63130516/BT6_63130516/Views/NhanViens63130516/TimKiem.cshtml
@model IEnumerable<BT6_63130516.Models.NhanVien>

@{
    ViewBag.Title = "TimKiem";
    Layout = "~/Views/Shared/_TrangChu.cshtml";
}

Nhập mã nhân viên cần tìm
@using (Html.BeginForm())
{
    <input type="text" name="maNV" />
    <input type="submit" value="Tìm kiếm" />
    <h3>DANH SÁCH NHÂN VIÊN</h3>

    <p>
        @Html.ActionLink("Create New", "Create")
    </p>
    <table class="table">
        <tr>
            <th>
                @Html.DisplayNameFor(model => model.HoNV)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.TenNV)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.GioiTinh)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.NgaySinh)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.Luong)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.AnhNV)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.DiaChi)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.PhongBan.TenPB)
            </th>
            <th></th>
        </tr>

        @foreach (var item in Model)
        {
            <tr>
                <td>
                    @Html.DisplayFor(modelItem => item.HoNV)
                </td>
                <td>
                    @Html.DisplayFor(modelItem => item.TenNV)
                </td>
                <td>
                    @Html.DisplayFor(modelItem => item.GioiTinh)
                </td>
                <td>
                    @Html.DisplayFor(modelItem => item.NgaySinh)
                </td>
                <td>
                    @Html.DisplayFor(modelItem => item.Luong)
                </td>
                <td>
                    @Html.DisplayFor(modelItem => item.AnhNV)
                </td>
                <td>
                    @Html.DisplayFor(modelItem => item.DiaChi)
                </td>
                <td>
                    @Html.DisplayFor(modelItem => item.PhongBan.TenPB)
                </td>
                <td>
                    @Html.ActionLink("Edit", "Edit", new { id = item.MaNV }) |
                    @Html.ActionLink("Details", "Details", new { id = item.MaNV }) |
                    @Html.ActionLink("Delete", "Delete", new { id = item.MaNV })
                </td>
            </tr>
        }

    </table>
}

BT6_63130516/BT6_63130516/Views/NhanViens63130516/TimKiemNC.cshtml
@model IEnumerable<BT6_63130516.Models.NhanVien>

@{
    ViewBag.Title = "TimKiemNC";
    Layout = "~/Views/Shared/_TrangChu.cshtml";
    var grid = new WebGrid(Model, canPage: true, defaultSort: "TenNV", rowsPerPage: 5);
    @Scripts.Render("~/Scripts/jquery-1.6.2.min.js")
}

<html>
<head>
    <style type="text/css">
        .grid-footer {
            color: #000;
            font: 17px Calibri;
            text-align: center;
            font-weight: bold;
        }

            .grid-footer a {
                background-color: #ffffff;
                color: blue;
                box-shadow: 0 4px 8px 0 rgba(0,0,0,0.2);
                padding: 1px 10px 2px 10px;
            }

                .grid-footer a:active, a:hover {
                    background-color: #ffffff;
                    color: #FFAD33;
                    box-shadow: 0 4px 8px 0 rgba(0,0,0,0.2);
                }

        .alternatingRowStyle {
            background-color: aliceblue;
        }

        table .table1 {
            text-align: left;
            margin-left: 0px;
            margin-right: 0px;
            width: 800px;
        }

        .tr, .td {
            text-align: left;
        }
    </style>
</head>
<body>
    <div>
        @using (Html.BeginForm("TimKiemNC", "NhanViens63130516", FormMethod.Get))
        {
            @Html.AntiForgeryToken()


            <table class="table1" align="center">
                <tr>
                    <td>
                        <div> Mã nhân viên</div>
                    </td>
                    <td>
                        <input type="text" name="maNV" value="@ViewBag.maNV" />
                    </td>

                </tr>
                <tr>
                    <td>Họ tên</td>
                    <td>
                        <input type="text" name="hoTen" value="@ViewBag.hoTen" />
                    </td>

                </tr>

                <tr>
                    <td>Giới tính</td>
                    <td>
                        @if (@ViewBag.gioiTinh == null)
                        {
                            <input type="radio" name="gioiTinh" value="1" /><text>Nam</text>
                            <input type="radio" name="gioiTinh" value="0" /><text>Nữ</text>
                        }
                        else if (@ViewBag.gioiTinh == "1")
                        {
                            <input type="radio" name="gioiTinh" checked value="1" /><text>Nam</text>
                            <input type="radio" name="gioiTinh" value="0" /><text>Nữ</text>
                        }
                        else
                        {
                            <input type="radio" name="gioiTinh" value="1" /><text>Nam</text>
                            <input type="radio" name="gioiTinh" checked value="0" /><text>Nữ</text>
                        }


                    </td>

                </tr>
                <tr>
                    <td>Lương từ</td>
                    <td>
                        <input type="text" name="luongMin" value="@ViewBag.luongMin" />
                        Đến<input type="text" name="luongMax" value="@ViewBag.luongMax" />
                    </td>

                </tr>

                <tr>
                    <td>Địa chỉ</td>
                    <td>
                        <input type="text" name="diaChi" value="@ViewBag.diaChi" />
                    </td>
                </tr>
                <tr>
                    <td>Phòng ban</td>
                    <td>
                        @Html.DropDownList("MaPB", null, "Tất cả", htmlAttributes: new { @class = "form-control" })
                    </td>
                </tr>
                <tr>
                    <td></td>
                    <td>
                        <input type="submit" name="submit" value="Tìm kiếm" style="margin-left: 5px;width:100px;
                background-color: blue;color:white" />
                        <input type="button" name="Nhapmoi" value="Nhập mới" style="margin-left: 5px;width:100px;
                background-color: blue;color:white" onclick="location.href='@Url.Action("TimKiemNC", "NhanViens63130516/TimKiemNC")'" />

                    </td>
                </tr>
            </table>
        }
    </div>
    <div id="gridContent">
        @ViewBag.TB
        @grid.GetHtml(
                 tableStyle: "table table-bordered table-hover",
                 footerStyle: "grid-footer",
                 fillEmptyRows: true,
                 mode: WebGridPagerModes.Numeric,
                 alternatingRowStyle: "alternatingRowStyle",
                   columns: new[]  // colums in grid
                  {
         grid.Column("STT",format: item => item.WebGrid.Rows.IndexOf(item) + 1 + Math.Round(Convert.ToDouble(grid.TotalRowCount / grid.PageCount) / grid.RowsPerPage) * grid.RowsPerPage * grid.PageIndex),
        grid.Column("MaNV","Mã nhân viên"), //the model fields to display
        grid.Column("HoNV","Họ nhân viên"  ),
        grid.Column("TenNV","Tên nhân viên"),
        grid.Column("GioiTinh","Giới tính",format: (@item) => @item.GioiTinh==true?"Nam":"Nữ"),
        grid.Column("NgaySinh","Ngày sinh",format:@<text> @item.NgaySinh.ToString("dd/MM/yyyy")</text>),
grid.Column("Luong","Tiền lương",format:@<text> @item.Luong.ToString("#,##0")</text>),
grid.Column("DiaChi","Địa chỉ"),
grid.Column("PHONGBAN.TenPB","Phòng ban"),
grid.Column(format: (item) => Html.ActionLink("Cập nhật", "Edit", "NhanViens63130516",new { id = item.MaNV },"NhanViens63130516Controller")),
grid.Column(format: (item) => Html.ActionLink("Xem chi tiết", "Details","NhanViens63130516", new { id = item.MaNV },"NhanViens63130516Controller")),
grid.Column(format: (item) => Html.ActionLink("Xóa", "Delete","NhanViens63130516", new { id = item.MaNV },"NhanViens63130516Controller")),
grid.Column("Chức năng", format: @<text>
    <a href="@Url.Action("Edit",
                        new { id = item.MaNV})" class="edit-btn"><abbr title="Cập nhật dữ liệu"><img src="/images/edit.png" width="20" height="20" /></abbr></a>
    <a href="@Url.Action("Details",
                        new { id = item.MaNV})" class="edit-btn"><abbr title="Xem chi tiết"><img src="/images/details.png" width="20" height="20" /></abbr></a>
    <a href="@Url.Action("Delete",
                        new { id = item.MaNV})" class="edit-btn">
        <abbr title="Xóa dữ liệu">
            <img src="/images/delete.png" width="20" height="20" />
        </abbr>
    </a>
</text>),

         }
         )
    </div>
</body>
</html>